package se.l4.silo.engine.search;

import se.l4.silo.engine.search.facets.Facet;

/**
 * Encounter used to supply extra information for a {@link IndexDefinition}
 * that might be generated by for example a {@link Facet}.
 *
 * @author Andreas Holstenson
 *
 */
public interface IndexDefinitionEncounter
{
	/**
	 * Add a field that will store values via {@link SearchFieldType#createValuesField(String, Language, Object)}.
	 *
	 * @param field
	 */
	void addValuesField(String field);
}
