package se.l4.silo.engine.index;

import java.io.IOException;
import java.io.InputStream;

import reactor.core.publisher.Flux;

/**
 * Updater of data stored in an {@link Index}. Applies data previously
 * generated by a {@link IndexDataGenerator}.
 */
public interface IndexDataUpdater
{
	/**
	 * Get the last hard commit that this index has performed.
	 *
	 * @return
	 */
	long getLastHardCommit();

	/**
	 * Get a flux that emits hard commits as they happen on this index.
	 *
	 * @return
	 */
	Flux<Long> hardCommits();

	/**
	 * Clear the index and reset {@link #getLastHardCommit()} to {@code 0}.
	 */
	void clear();

	/**
	 * Apply previously generated data.
	 *
	 * @param opId
	 * @param dataId
	 * @param in
	 */
	void apply(long opId, long dataId, InputStream in)
		throws IOException;

	/**
	 * Delete something from this query engine.
	 *
	 * @param opId
	 * @param dataId
	 */
	void delete(long opId, long dataId);
}
